name: worker-ci

on:
  push:
    paths:
      - "Worker/**"
      - ".github/workflows/Worker-ci.yml"
  pull_request:
    paths:
      - "Worker/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Worker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run test
      - run: npx tsc --noEmit
