name: pages-functions-ci

on:
  push:
    paths:
      - "Worker/**"
      - "functions/**"
      - "Frontend/**"
      - "functions/**"
      - "Frontend/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/Worker-ci.yml"
  pull_request:
    paths:
      - "Worker/**"
      - "functions/**"
      - "Frontend/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: cd Worker && npm install
      - run: cd Worker && npm run test

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
